version: "3.9"
services:
  spigot:
    build:
      dockerfile: spigot.dockerfile
      context: .
    volumes:
      - spigot-data:/spigotmc/persist:rw
    ports:
      - target: "29565"
        published: "29565"
        protocol: tcp
        mode: host
      - "127.0.0.1:29575:29575"
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '4G'
        reservations:
          cpus: '1.0'
          memory: '2G'
    restart: unless-stopped
volumes:
  spigot-data: