version: "3.9"
services:
  mariadb:
    image: mariadb
    volumes:
      - type: bind
        source: /var/gerrit/msm8916-gerrit/sql
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: bind
        source: /var/gerrit/msm8916-gerrit/secrets
        target: /secrets
        read_only: true
      - type: volume
        source: reviewdb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secrets/pw
      MYSQL_DATABASE_FILE: /secrets/db
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '200M'
        reservations:
          cpus: '0.5'
          memory: '50M'
    expose:
      - "3306"
    restart: unless-stopped
  msm8916-gerrit:
    build:
      context: .
      dockerfile: msm8916.dockerfile
    volumes:
      - type: bind
        source: /var/gerrit/msm8916-gerrit
        target: /gerrit
        volume:
          nocopy: true
    depends_on:
      - mariadb
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '1.5G'
        limits:
          cpus: '2.0'
          memory: '3G'
    ports:
      - "29418:29418"
      - "8080:8080"
    restart: unless-stopped
  tasker-gerrit:
    build:
      context: .
      dockerfile: tasker.dockerfile
    volumes:
      - type: bind
        source: /var/gerrit/tasker-gerrit
        target: /gerrit
        volume:
          nocopy: true
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '1G'
        limits:
          cpus: '1.5'
          memory: '2G'
    ports:
      - "8083:8080"
      - "29420:29420"
    restart: unless-stopped
  zvikaramba-gerrit:
    build:
      context: .
      dockerfile: zvikaramba.dockerfile
    volumes:
      - type: bind
        source: /var/gerrit/zvikaramba-gerrit
        target: /gerrit
        volume:
          nocopy: true
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '1G'
        limits:
          cpus: '1.5'
          memory: '2G'
    ports:
      - "8084:8080"
      - "29421:29421"
    restart: unless-stopped
volumes:
  reviewdb:
