version: "3.7"
volumes:
  ovpn-data-udp:
    external: true
  ovpn-data-tcp:
    external: true
services:
  openvpn-udp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-udp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/udp"
    expose:
      - "5555"
    restart: unless-stopped
  openvpn-tcp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-tcp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/tcp"
    expose:
      - "5555"
    restart: unless-stopped
  openvpn-monitor:
    image: ruimarinho/openvpn-monitor
    environment:
      - OPENVPNMONITOR_DEFAULT_SITE=Home
      - OPENVPNMONITOR_DEFAULT_MAPS=True
      - OPENVPNMONITOR_SITES_0_ALIAS=OpenVPN UDP
      - OPENVPNMONITOR_SITES_0_HOST=openvpn-udp
      - OPENVPNMONITOR_SITES_0_PORT=5555
      - OPENVPNMONITOR_SITES_0_SHOWDISCONNECT=True
      - OPENVPNMONITOR_SITES_1_ALIAS=OpenVPN TCP
      - OPENVPNMONITOR_SITES_1_HOST=openvpn-tcp
      - OPENVPNMONITOR_SITES_1_PORT=5555
      - OPENVPNMONITOR_SITES_1_SHOWDISCONNECT=True
    ports:
      - "2080:80"
    links:
      - openvpn-udp
      - openvpn-tcp
    restart: unless-stopped
