version: "3.9"
volumes:
  ovpn-data-udp:
    external: true
  ovpn-data-tcp:
    external: true
services:
  openvpn-udp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-udp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/udp"
    expose:
      - "5555"
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '20M'
        limits:
          cpus: '2.0'
          memory: '100M'
    restart: unless-stopped
  openvpn-tcp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-tcp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/tcp"
    expose:
      - "5555"
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: '20M'
        limits:
          cpus: '2.0'
          memory: '100M'
    restart: unless-stopped
  openvpn-monitor:
    build:
      context: .
      dockerfile: monitor.dockerfile
    ports:
      - "2080:8080"
    links:
      - openvpn-udp
      - openvpn-tcp
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: '50M'
        limits:
          cpus: '0.5'
          memory: '100M'
    restart: unless-stopped
