version: "3.7"
volumes:
  ovpn-data-udp:
    external: true
  ovpn-data-tcp:
    external: true
services:
  openvpn-udp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-udp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/udp"
    expose:
      - "5555"
    restart: unless-stopped
  openvpn-tcp:
    image: kylemanna/openvpn
    volumes:
      - ovpn-data-tcp:/etc/openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "21195:1194/tcp"
    expose:
      - "5555"
    restart: unless-stopped
  openvpn-monitor:
    build:
      context: .
      dockerfile: monitor.dockerfile
    ports:
      - "2080:8080"
    links:
      - openvpn-udp
      - openvpn-tcp
    restart: unless-stopped
